apiVersion: v1
kind: Secret
metadata:
  name: {{.Release.Name}}-webhook
type: Opaque
data:
  {{- $caCert := "" }}
  {{- if .Values.tls.helmCertGen }}
  {{- $cn := printf "%s-webhook.%s.svc" .Release.Name .Release.Namespace }}
  {{- $ca := genCA (printf "%s-webhook-ca" .Release.Name  ) 36500 }}
  {{- $cert := genSignedCert $cn (list "127.0.0.1") (list $cn "localhost") 36500 $ca }}
  ca.crt: {{ $ca.Cert | b64enc }}
  tls.crt: {{ $cert.Cert | b64enc }}
  tls.key: {{ $cert.Key | b64enc }}
  {{- $caCert = $ca.Cert | b64enc }}
  {{- else }}
  ca.crt: {{.Values.tls.caCert}}
  tls.crt: {{.Values.tls.clientCert }}
  tls.key: {{ .Values.tls.clientKey }}
  {{- $caCert := .Values.tls.caCert }}
  {{- end }}

---

apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{.Release.Name}}-webhook
webhooks:
  {{- range $moduleName, $module := fromYaml .Values.modules }}
  - name: {{$moduleName}}.operator.kyma-project.io
  {{- if $module.labels }}
    objectSelector:
      matchLabels:
        {{ $module.labels | toYaml }}
  {{- end }}
    admissionReviewVersions:
      - v1
    clientConfig:
      caBundle: {{ $caCert }}
      service:
        name: {{$.Release.Name}}-webhook
        namespace: {{$.Release.Namespace}}
        path: /validate/{{$moduleName}}
    rules:
      - apiGroups:
          - "operator.kyma-project.io"
        apiVersions:
          - "*"
        operations:
          - CREATE
          - UPDATE
          - DELETE
        resources:
        {{- if not $module.statusOnly }}
          - "*"
        {{- else }}
          - "*/status"
        {{- end }}
    sideEffects: NoneOnDryRun
    timeoutSeconds: 15
    failurePolicy: Ignore
  {{- end }}
