name: 'config'
type: 'yaml'
relation: 'local'
input:
  type: "file"
  path: "./data/config.yaml" # path is relative to the current resource file
  mediaType: "application/yaml" # optional, will be defaulted to application/octet-stream
---
name: 'nginx-ingress'
type: 'helm-chart'
relation: 'local'
input:
  type: 'dir'
  compress: true
  path: "./data/nginx-ingress" # path is relative to the current resource file
---
name: 'crds'
type: 'crds'
relation: 'local'
input:
  type: 'dir'
  compress: true
  path: "./data/nginx-ingress/crds" # path is relative to the current resource file