module-name: lifecycle-manager
protecode:
  - europe-docker.pkg.dev/kyma-project/prod/lifecycle-manager:latest
  - europe-docker.pkg.dev/kyma-project/prod/lifecycle-manager:1.1.0
whitesource:
  language: golang-mod
  exclude:
    - "**/test/**"
    - "**/*_test.go"
    - "**/testutils/**"
    - "tests/**"
  subprojects: false
