module-name: lifecycle-manager
kind: kcp
checkmarxOne:
  checkmarx_preset: golang
protecode:
  - europe-docker.pkg.dev/kyma-project/prod/lifecycle-manager:1.2.3
whitesource:
  language: golang-mod
  exclude:
    - "**/test/**"
    - "**/*_test.go"
    - "**/testutils/**"
    - "tests/**"
  subprojects: false
