module-name: lifecycle-manager
kind: kcp
checkmarx-one:
  preset: go-default
  exclude:
    - "**/test/**"
    - "**/*_test.go"
    - "**/testutils/**"
    - "tests/**"
bdba:
  - europe-docker.pkg.dev/kyma-project/prod/lifecycle-manager:1.9.3
  - europe-docker.pkg.dev/kyma-project/prod/lifecycle-manager:latest
mend:
  language: golang-mod
  exclude:
    - "**/test/**"
    - "**/*_test.go"
    - "**/testutils/**"
    - "tests/**"
