apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
- operator_v1alpha1_watcher.yaml

generatorOptions:
  disableNameSuffixHash: true

patches:
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --enable-kcp-watcher=true
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --enable-webhook-pre-install-check=true
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --skr-watcher-path=/skr-webhook      
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --requeue-success-interval=10m     
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --requeue-waiting-interval=5s      
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --requeue-failure-interval=5s
    target:
      kind: Deployment
