apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: manager-rolebinding-manifest
  namespace: kcp-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: manager-role-manifest
subjects:
  - kind: ServiceAccount
    name: controller-manager
    namespace: system