apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: controller-manager
  namespace: system
spec:
  action: ALLOW
  rules:
    - to:
        - operation:
            paths:
              - /metrics
              - /v1*
              - /convert
              - /validate
              - /mutate
  selector:
    matchLabels:
      app.kubernetes.io/component: lifecycle-manager.kyma-project.io
