apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: controller-manager-webhook-serving  # this name should match the one appeared in kustomizeconfig.yaml
spec:
  secretName: lifecycle-manager-webhook-server-cert # this secret will not be prefixed, since it's not managed by kustomize