# -- Replicas
replicas: 1
image:
  # -- Image repository
  repository: redis
  # -- Image tag
  tag: 5.0.4
  # -- Image pull policy
  pullPolicy: ""
# -- Image pull secrets
imagePullSecrets: []
# -- Pod security content
podSecurityContext: {}
# -- Node selector
nodeSelector: {}
# -- Affinity settings
affinity: {}
# -- Tolerations
tolerations: []
# -- Priority class
priorityClassName: ""
# -- Security context
securityContext: {}
resources:
  limits:
    # -- Memory limit
    memory: 200Mi
    # -- CPU limit
    cpu: 0.1
  requests:
    # -- Memory request
    memory: 20Mi
    # -- CPU request
    cpu: 0.01