apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - service_account.yaml
  - manager_role.yaml
  - manager_role_binding.yaml
  - leader_election_role.yaml
  - leader_election_role_binding.yaml
  - crd_cluster_role.yaml
  - crd_cluster_role_binding.yaml
