# permissions for end users to view samples.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sample-viewer-role
rules:
- apiGroups:
  - component.kyma-project.io
  resources:
  - samples
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - component.kyma-project.io
  resources:
  - samples/status
  verbs:
  - get
