apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-ingress-override
  namespace: default
  labels:
    extension.kyma-project.io/config-override: a
    operator.kyma-project.io/override-type: helm-values
data:
  values.yaml: |
    fullNameOverride=ft-123
    testKey=testValue
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-ingress-override-2
  namespace: default
  labels:
    extension.kyma-project.io/config-override: b
    operator.kyma-project.io/override-type: helm-values
    operator.kyma-project.io/managed-by: kyma-operator
data:
  values.yaml: |
    fullNameOverride=ft-123
    testKey=testValue