apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: kcp-system
spec:
  template:
    spec:
      containers:
        - name: manager
          volumeMounts:
            - name: maintenance-policy
              mountPath: /etc/maintenance-policy
              readOnly: true
      volumes:
        - name: maintenance-policy
          configMap:
            name: maintenance-config
