# The following manifests contain a self-signed issuer CR and a certificate CR.
# More document can be found at https://docs.cert-manager.io
# WARNING: Targets CertManager v1.0. Check https://cert-manager.io/docs/installation/upgrading/ for breaking changes.
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: controller-manager-selfsigned
  namespace: kcp-system
spec:
  selfSigned: { }
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: controller-manager-webhook-serving
  namespace: kcp-system
spec:
  commonName: klm-controller-manager-webhook-serving
  subject:
    organizationalUnits:
      - "BTP Kyma Runtime"
    organizations:
      - "SAP SE"
    localities:
      - "Walldorf"
    provinces:
      - "Baden-WÃ¼rttemberg"
    countries:
      - "DE"
  # $(SERVICE_NAME) and $(SERVICE_NAMESPACE) will be substituted by kustomize
  dnsNames:
    - $(SERVICE_NAME).$(SERVICE_NAMESPACE).svc
    - $(SERVICE_NAME).$(SERVICE_NAMESPACE).svc.cluster.local
  issuerRef:
    kind: Issuer
    name: controller-manager-selfsigned
  secretName: klm-controller-manager-webhook # this secret will not be prefixed, since it's not managed by kustomize
