# The main purpose of this dedicated kustomization is to have separate resources configuration for load tests. Unlike the default setup, it enables the ability to configure additional components that we do not want in the default configuration (e.g. vendor-specific gateway implementation) but want to test for load anyhow.
resources:
  - metrics_cluster_role_binding.yaml
  - metrics_role.yaml
  - metrics_role_binding.yaml
  - ../manager
  - ../certmanager

generatorOptions:
  disableNameSuffixHash: true

# Adds namespace to all resources.
namespace: kcp-system
namePrefix: klm-

# Labels to add to all resources and selectors.
commonLabels:
  app.kubernetes.io/component: lifecycle-manager.kyma-project.io
  app.kubernetes.io/instance: kcp-lifecycle-manager-main
  app.kubernetes.io/name: kcp-lifecycle-manager
  app.kubernetes.io/created-by: kustomize
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: manual-deployment

replacements:
  # substitutes CERTIFICATE_NAMESPACE, the namespace of the certificate CR
  - source:
      kind: Certificate
      name: serving-cert # this name should match the one in certificate.yaml
      fieldPath: metadata.namespace
    targets:
      - select:
          kind: ValidatingWebhookConfiguration
          name: validating-webhook-configuration
        fieldpaths:
          - metadata.annotations.[cert-manager.io/inject-ca-from]
        options:
          delimiter: '/'
          index: 0
      - select:
          kind: CustomResourceDefinition
        fieldpaths:
          - metadata.annotations.[cert-manager.io/inject-ca-from]
        options:
          delimiter: '/'
          index: 0
  # substitutes CERTIFICATE_NAME, the name of the certificate CR
  - source:
      kind: Certificate
      name: serving-cert # this name should match the one in certificate.yaml
      fieldPath: metadata.name
    targets:
      - select:
          kind: ValidatingWebhookConfiguration
          name: validating-webhook-configuration
        fieldpaths:
          - metadata.annotations.[cert-manager.io/inject-ca-from]
        options:
          delimiter: '/'
          index: 1
      - select:
          kind: CustomResourceDefinition
        fieldpaths:
          - metadata.annotations.[cert-manager.io/inject-ca-from]
        options:
          delimiter: '/'
          index: 1
  # substitutes SERVICE_NAMESPACE, the namespace of the service
  - source:
      kind: Service
      version: v1
      name: webhook-service
      fieldpath: metadata.namespace
    targets:
      - select:
          group: cert-manager.io
          version: v1
          kind: Certificate
          name: serving-cert
        fieldpaths:
          - spec.dnsNames.0
          - spec.dnsNames.1
        options:
          delimiter: '.'
          index: 1
  # substitutes SERVICE_NAME, the name of the service
  - source:
      kind: Service
      version: v1
      name: webhook-service
      fieldpath: metadata.name
    targets:
      - select:
          group: cert-manager.io
          version: v1
          kind: Certificate
          name: serving-cert
        fieldpaths:
          - spec.dnsNames.0
          - spec.dnsNames.1
        options:
          delimiter: '.'
          index: 0

patches:
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --pprof=true
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --in-kcp-mode
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --log-level=9
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Always
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --rate-limiter-burst=2000
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --rate-limiter-frequency=1000
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --max-concurrent-manifest-reconciles=25
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --max-concurrent-kyma-reconciles=50
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --cache-sync-timeout=60m
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --failure-max-delay=30s
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --kyma-requeue-success-interval=1m
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --manifest-requeue-success-interval=1m
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --watcher-requeue-success-interval=1m
    target:
      kind: Deployment
  - path: patches/adjust_resources_in_deployment.yaml
  # Mount the controller config file for loading manager configurations
  # through a ComponentConfig type
  #  - manager_config_patch.yaml
  # [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix including the one in
  # crd/kustomization.yaml
  - path: manager_webhook_patch.yaml
  # [CERTMANAGER] To enable cert-manager, uncomment all sections with 'CERTMANAGER'.
  # Uncomment 'CERTMANAGER' sections in crd/kustomization.yaml to enable the CA injection in the admission webhooks.
  # 'CERTMANAGER' needs to be enabled to use ca injection
  - path: webhookcainjection_patch.yaml

components:
  - ../crd
  - ../rbac
  # [ISTIO] To enable istio, uncomment all sections with 'ISTIO'.
#  - ../istio
  # [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix including the one in
  # crd/kustomization.yaml
  - ../webhook
  # [PROMETHEUS] To enable prometheus monitor, uncomment all sections with 'PROMETHEUS'.
  - ../prometheus
  # [GRAFANA] To generate configmap for provision grafana dashboard
  - ../grafana
