---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.9.2
  creationTimestamp: null
  name: watchers.operator.kyma-project.io
spec:
  group: operator.kyma-project.io
  names:
    kind: Watcher
    listKind: WatcherList
    plural: watchers
    singular: watcher
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: Watcher is the Schema for the watchers API.
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: WatcherSpec defines the desired state of Watcher.
            properties:
              field:
                description: Field describes the subresource that should be watched
                  Value can be one of ("spec", "status")
                enum:
                - spec
                - status
                type: string
              labelsToWatch:
                additionalProperties:
                  type: string
                description: LabelsToWatch describes the labels that should be watched
                type: object
              serviceInfo:
                description: ServiceInfo describes the service information of the
                  operator
                properties:
                  name:
                    description: Name describes the service name.
                    type: string
                  namespace:
                    description: Namespace describes the service namespace.
                    type: string
                  port:
                    description: Port describes the service port.
                    format: int64
                    type: integer
                required:
                - name
                - namespace
                - port
                type: object
            required:
            - field
            - labelsToWatch
            - serviceInfo
            type: object
          status:
            description: WatcherStatus defines the observed state of Watcher.
            properties:
              conditions:
                description: List of status conditions to indicate the status of a
                  Watcher.
                items:
                  description: WatcherCondition describes condition information for
                    Watcher.
                  properties:
                    lastTransitionTime:
                      description: Timestamp for when Watcher last transitioned from
                        one status to another.
                      format: date-time
                      type: string
                    message:
                      description: Human-readable message indicating details about
                        the last status transition.
                      type: string
                    reason:
                      description: Machine-readable text indicating the reason for
                        the condition's last transition.
                      type: string
                    status:
                      description: Status of the Watcher Condition. Value can be one
                        of ("True", "False", "Unknown").
                      enum:
                      - "True"
                      - "False"
                      - Unknown
                      type: string
                    type:
                      description: Type is used to reflect what type of condition
                        we are dealing with. Most commonly WatcherConditionTypeReady
                        it is used as extension marker in the future.
                      enum:
                      - Ready
                      type: string
                  required:
                  - status
                  - type
                  type: object
                type: array
              observedGeneration:
                description: ObservedGeneration
                format: int64
                type: integer
              state:
                description: State signifies current state of a Watcher. Value can
                  be one of ("Ready", "Processing", "Error", "Deleting")
                enum:
                - Processing
                - Deleting
                - Ready
                - Error
                type: string
            required:
            - state
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
