name: "Create Release For KLM API Module"
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Semantic version to release (e.g. 1.2.3 or v1.2.3)"
        required: true
permissions:
  contents: read

jobs:
  call-create-release:
    permissions:
      contents: write
    uses: ./.github/workflows/create-release-go-module.yml
    with:
      version: ${{ github.event.inputs.version }}
      module: github.com/kyma-project/lifecycle-manager/api
      module_dir: api
      go_version_file: api/go.mod
      go_sum_file: api/go.sum
    secrets: inherit
