name: Report Sprint Test Suites
run-name: A report for sprint commits

permissions: { }

# The report generation is performed ad hoc via manual invocation.
on: workflow_dispatch

env:
  reporter: ${{ github.workspace }}/scripts/coverage-metrics/bin/utils/commit-test-suites/gauge-sprint-commits.py
  pip_requirements: ${{ github.workspace }}/scripts/coverage-metrics/bin/utils/commit-test-suites/requirements.txt

jobs:
  generate-report:
    runs-on: ubuntu-latest
    steps:
      - name: Check out report scripts
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          repository: kyma-project/qa-toolkit
          path: scripts
      - name: Adjust the report scripts
        run: |
          chmod a+x $reporter
          python -m pip install --upgrade pip
          pip install -r $pip_requirements
      - name: Generate a report
        run: |
          $reporter --repo-url https://github.com/kyma-project/lifecycle-manager.git --days 14 --e2e tests/e2e --integration tests/integration
