# The following manifests contain a self-signed issuer CR and a certificate CR.
# More document can be found at https://docs.cert-manager.io
# WARNING: Targets CertManager v1.0. Check https://cert-manager.io/docs/installation/upgrading/ for breaking changes.

apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: watcher-selfsigned-cluster-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: watcher-selfsigned-issuer
  namespace: istio-system
  labels:
    operator.kyma-project.io/purpose: "klm-watcher-cert-manager"
    operator.kyma-project.io/managed-by: "lifecycle-manager"
spec:
  ca:
    secretName: klm-watcher-root-secret
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: watcher-serving-cert  # this name should match the one appeared in kustomizeconfig.yaml
  namespace: istio-system
spec:
  dnsNames:
    - 'listener.kyma.cloud.sap' # this dnsNames should be overwritten based on deployment environment
  isCA: true
  commonName: klm-watcher-selfsigned-ca
  secretName: klm-watcher-root-secret # this secret will not be prefixed, since it's not managed by kustomize
  secretTemplate:
    labels:
      operator.kyma-project.io/managed-by: "lifecycle-manager"
  privateKey:
    algorithm: RSA
  issuerRef:
    name: lifecycle-manager-watcher-selfsigned-cluster-issuer # this needs to match the prefixed ClusterIssuer
    kind: ClusterIssuer
    group: cert-manager.io
---

