apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
- operator_v1beta2_watcher.yaml
- gateway.yaml
- certificate_setup.yaml
generatorOptions:
  disableNameSuffixHash: true

patches:
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --enable-kcp-watcher
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --skr-watcher-path=/skr-webhook
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --skr-watcher-image-tag=v20240206-d3903ab2
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --enable-domain-name-pinning=true
    target:
      kind: Deployment
