apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
generatorOptions:
  disableNameSuffixHash: true
resources:
  - gateway.yaml
  - kyma_watcher.yaml
patches:
  - target:
      kind: Deployment
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --skr-watcher-image-tag=2.1.3
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --skr-watcher-image-registry=europe-docker.pkg.dev/kyma-project/prod
