apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
- operator_v1alpha1_watcher.yaml
- gateway.yaml
- certificate_setup.yaml
generatorOptions:
  disableNameSuffixHash: true

patches:
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --enable-kcp-watcher
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --skr-watcher-path=/skr-webhook
    target:
      kind: Deployment
