apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

configMapGenerator:
  - name: maintenance-config
    files:
      - policy.json

generatorOptions:
  disableNameSuffixHash: true

patches:
  - path: patches/volume_mount.yaml
    target:
      kind: Deployment
      name: klm-controller-manager
      namespace: kcp-system

transformers:
  - |-
    apiVersion: builtin
    kind: NamespaceTransformer
    metadata:
      name: add-maintwindows-cm-to-kcp-system
      namespace: kcp-system
    unsetOnly: true